### ISSUE TITLE
npm install 404

### ISSUE THREAD

**Issue by qinlue** [MoMask/react-native-ok-gesture-password#1]
script:  npm install react-native-ok-gesture-password --save

 ERR! code E404
npm ERR! 404 Not Found: react-native-ok-gesture-password@latest

**Comment by MoMask** [comment]
> 脚本：npm install react-native-ok-gesture-password --save
> 
> 呃！代码E404 
> npm ERR！404 Not Found：react-native-ok-gesture-password @ latest

sorry, it work now

**Comment by MoMask** [comment]
> script: npm install react-native-ok-gesture-password --save
> 
> ERR! code E404
> npm ERR! 404 Not Found: react-native-ok-gesture-password@latest

sorry,it work now.
